# root
GET http://localhost:3002/filter?param=quantity&val=3
Accept: application/json
###

GET http://localhost:3002/max-price
###

GET http://localhost:3002/format
Accept: application/json
###

POST http://localhost:3002/addArray
content-type: application/json

[
  {"type":"socks", "color":"red", "quantity":10, "priceForPair":"$3"},
  {"type":"socks", "color":"green", "quantity":5, "priceForPair":"$10"},
  {"type":"socks", "color":"blue", "quantity":8, "priceForPair":"$6"},
  {"type":"hat", "color":"red", "quantity":7, "price":"$5"},
  {"type":"hat", "color":"green", "quantity":0, "price":"$6"},
  {"type":"socks", "color":"blue", "priceForPair":"$6"},
  {"type":"socks", "color":"red", "quantity":10, "priceForPair":"$3"},
  {"type":"socks", "color":"white", "quantity":3, "priceForPair":"$4"},
  {"type":"socks", "color":"green", "priceForPair":"$10"},
  {"type":"socks", "color":"blue", "quantity":2, "priceForPair":"$6"},
  {"type":"hat", "color":"green", "quantity":3, "price":"$5"},
  {"type":"hat", "color":"red", "quantity":1, "price":"$6"},
  {"type":"socks", "color":"blue", "priceForPair":"$6"},
  {"type":"socks", "color":"blue", "quantity":15, "priceForPair":"$15"}

]

###

POST http://localhost:3002/source?type=json
Accept: application/json

###

POST http://localhost:3002/source?type=store
Accept: application/json

###Get Discount with callback
GET http://localhost:3002/callback

###Get Discount with promise
GET http://localhost:3002/promise

###Get Discount with async-await
GET http://localhost:3002/async-await

###Get all files in uploads
GET http://localhost:3002/upload


###Convert csv to json
http://localhost:3002/store/csv


###Optimize json parse from csv
POST http://localhost:3002/optimize-json
content-type: application/json